# Generated by Django 6.0.1 on 2026-01-26 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('type', models.CharField(choices=[('appartement', 'Appartement'), ('villa', 'Villa'), ('maison', 'Maison'), ('studio', 'Studio'), ('duplex', 'Duplex')], max_length=20, verbose_name='type')),
                ('city', models.CharField(choices=[('abidjan', 'Abidjan'), ('yamoussoukro', 'Yamoussoukro'), ('bouake', 'Bouaké'), ('san_pedro', 'San-Pédro'), ('korhogo', 'Korhogo'), ('daloa', 'Daloa'), ('man', 'Man')], max_length=50, verbose_name='ville')),
                ('neighborhood', models.CharField(max_length=100, verbose_name='quartier')),
                ('address', models.TextField(verbose_name='adresse complète')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('bedrooms', models.PositiveIntegerField(default=1, verbose_name='nombre de chambres')),
                ('bathrooms', models.PositiveIntegerField(default=1, verbose_name='nombre de salles de bain')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='capacité (personnes)')),
                ('surface_area', models.PositiveIntegerField(blank=True, null=True, verbose_name='superficie (m²)')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix par nuit (FCFA)')),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='frais de ménage (FCFA)')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='WiFi')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Climatisation')),
                ('has_tv', models.BooleanField(default=False, verbose_name='Télévision')),
                ('has_kitchen', models.BooleanField(default=False, verbose_name='Cuisine équipée')),
                ('has_parking', models.BooleanField(default=False, verbose_name='Parking')),
                ('has_pool', models.BooleanField(default=False, verbose_name='Piscine')),
                ('has_security', models.BooleanField(default=False, verbose_name='Gardiennage/Sécurité')),
                ('has_generator', models.BooleanField(default=False, verbose_name='Groupe électrogène')),
                ('allow_pets', models.BooleanField(default=False, verbose_name='Animaux autorisés')),
                ('allow_smoking', models.BooleanField(default=False, verbose_name='Fumeur autorisé')),
                ('min_nights', models.PositiveIntegerField(default=1, verbose_name='nombre minimum de nuits')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifiée')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('bookings_count', models.PositiveIntegerField(default=0, verbose_name='nombre de réservations')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note moyenne')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'avis")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residences', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'résidence',
                'verbose_name_plural': 'résidences',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='residences/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('is_primary', models.BooleanField(default=False, verbose_name='image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='residences.residence', verbose_name='résidence')),
            ],
            options={
                'verbose_name': 'image de résidence',
                'verbose_name_plural': 'images de résidence',
                'ordering': ['order', '-is_primary'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('is_available', models.BooleanField(default=True, verbose_name='disponible')),
                ('custom_price', models.DecimalField(blank=True, decimal_places=2, help_text='Laisser vide pour utiliser le prix par défaut', max_digits=10, null=True, verbose_name='prix personnalisé (FCFA)')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='residences.residence', verbose_name='résidence')),
            ],
            options={
                'verbose_name': 'disponibilité',
                'verbose_name_plural': 'disponibilités',
                'ordering': ['date'],
                'unique_together': {('residence', 'date')},
            },
        ),
    ]
