# Generated by Django 6.0.1 on 2026-02-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('residences', '0002_alter_residence_price_per_night'),
    ]

    operations = [
        migrations.AddField(
            model_name='residenceimage',
            name='platform_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
