# Generated by Django 6.0.1 on 2026-02-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='Présentation du propriétaire', verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, help_text='Pour les propriétaires professionnels', max_length=200, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AddField(
            model_name='user',
            name='verified_owner',
            field=models.BooleanField(default=False, help_text="Propriétaire dont l'identité a été vérifiée", verbose_name='Propriétaire vérifié'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('proprietaire', 'Propriétaire'), ('both', 'Client et Propriétaire'), ('admin', 'Administrateur')], default='client', max_length=20, verbose_name='type utilisateur'),
        ),
    ]
