# Generated by Django 6.0.1 on 2026-02-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_user_bio_user_business_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('client', 'Client'), ('proprietaire_vehicule', 'Propriétaire de véhicules'), ('proprietaire_residence', 'Propriétaire de résidences'), ('proprietaire', 'Propriétaire (véhicules et résidences)'), ('admin', 'Administrateur')], default='client', max_length=30, verbose_name='type utilisateur'),
        ),
    ]
