# Generated by Django 6.0.1 on 2026-02-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='moov_money_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Moov Money'),
        ),
        migrations.AddField(
            model_name='user',
            name='mtn_money_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro MTN Money'),
        ),
        migrations.AddField(
            model_name='user',
            name='orange_money_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Orange Money'),
        ),
        migrations.AddField(
            model_name='user',
            name='wave_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Wave'),
        ),
    ]
