# Generated by Django 6.0.1 on 2026-01-26 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID de transaction')),
                ('external_transaction_id', models.CharField(blank=True, help_text='ID fourni par le prestataire de paiement', max_length=200, verbose_name='ID transaction externe')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='devise')),
                ('platform_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='commission plateforme (FCFA)')),
                ('owner_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant propriétaire (FCFA)')),
                ('payment_method', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('card', 'Carte bancaire'), ('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire')], max_length=30, verbose_name='méthode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='statut')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='numéro de téléphone')),
                ('card_last4', models.CharField(blank=True, max_length=4, verbose_name='4 derniers chiffres carte')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='métadonnées')),
                ('error_message', models.TextField(blank=True, verbose_name="message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de complétion')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bookings.booking', verbose_name='réservation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='utilisateur')),
            ],
            options={
                'verbose_name': 'paiement',
                'verbose_name_plural': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payout_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID de versement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant (FCFA)')),
                ('payment_method', models.CharField(max_length=50, verbose_name='méthode')),
                ('account_details', models.TextField(verbose_name='détails du compte')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de complétion')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
                ('payments', models.ManyToManyField(related_name='payouts', to='payments.payment', verbose_name='paiements inclus')),
            ],
            options={
                'verbose_name': 'versement',
                'verbose_name_plural': 'versements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(editable=False, max_length=100, unique=True, verbose_name='ID de remboursement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant remboursé (FCFA)')),
                ('reason', models.CharField(choices=[('cancellation', 'Annulation de réservation'), ('error', 'Erreur de paiement'), ('duplicate', 'Paiement en double'), ('other', 'Autre')], max_length=20, verbose_name='raison')),
                ('reason_details', models.TextField(blank=True, verbose_name='détails')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Complété'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='date de complétion')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment', verbose_name='paiement')),
            ],
            options={
                'verbose_name': 'remboursement',
                'verbose_name_plural': 'remboursements',
                'ordering': ['-created_at'],
            },
        ),
    ]
