# Generated by Django 6.0.1 on 2026-02-04 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='checkout_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='URL de paiement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='external_id',
            field=models.CharField(blank=True, help_text='Token PayDunya', max_length=200, verbose_name='ID PayDunya'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='owner_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='montant propriétaire (FCFA)'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('mobile_money', 'Mobile Money'), ('orange_money', 'Orange Money'), ('mtn_money', 'MTN Money'), ('moov_money', 'Moov Money'), ('wave', 'Wave'), ('card', 'Carte bancaire'), ('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire')], default='mobile_money', max_length=30, verbose_name='méthode de paiement'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En attente'), ('processing', 'En cours'), ('COMPLETED', 'Complété'), ('FAILED', 'Échoué'), ('PAID', 'Payé'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='PENDING', max_length=20, verbose_name='statut'),
        ),
    ]
