# Generated by Django 6.0.1 on 2026-01-26 08:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('description', models.TextField(verbose_name='description')),
                ('brand', models.CharField(max_length=50, verbose_name='marque')),
                ('model', models.CharField(max_length=50, verbose_name='modèle')),
                ('year', models.PositiveIntegerField(verbose_name='année')),
                ('type', models.CharField(choices=[('citadine', 'Citadine'), ('berline', 'Berline'), ('suv', 'SUV/4x4'), ('minibus', 'Minibus'), ('pickup', 'Pick-up'), ('moto', 'Moto')], max_length=20, verbose_name='type')),
                ('transmission', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20, verbose_name='transmission')),
                ('fuel_type', models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20, verbose_name='carburant')),
                ('seats', models.PositiveIntegerField(default=5, verbose_name='nombre de places')),
                ('doors', models.PositiveIntegerField(default=4, verbose_name='nombre de portes')),
                ('color', models.CharField(max_length=50, verbose_name='couleur')),
                ('plate_number', models.CharField(max_length=20, unique=True, verbose_name='immatriculation')),
                ('city', models.CharField(choices=[('abidjan', 'Abidjan'), ('yamoussoukro', 'Yamoussoukro'), ('bouake', 'Bouaké'), ('san_pedro', 'San-Pédro'), ('korhogo', 'Korhogo'), ('daloa', 'Daloa'), ('man', 'Man')], max_length=50, verbose_name='ville')),
                ('pickup_location', models.TextField(verbose_name='lieu de récupération')),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix par jour (FCFA)')),
                ('price_with_driver', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='prix avec chauffeur par jour (FCFA)')),
                ('deposit', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='caution (FCFA)')),
                ('insurance_included', models.BooleanField(default=True, verbose_name='assurance incluse')),
                ('insurance_type', models.CharField(blank=True, max_length=100, verbose_name="type d'assurance")),
                ('has_ac', models.BooleanField(default=True, verbose_name='Climatisation')),
                ('has_gps', models.BooleanField(default=False, verbose_name='GPS')),
                ('has_bluetooth', models.BooleanField(default=False, verbose_name='Bluetooth')),
                ('has_usb', models.BooleanField(default=False, verbose_name='Port USB')),
                ('has_spare_tire', models.BooleanField(default=True, verbose_name='Roue de secours')),
                ('has_first_aid_kit', models.BooleanField(default=True, verbose_name='Trousse de secours')),
                ('has_child_seat', models.BooleanField(default=False, verbose_name='Siège bébé disponible')),
                ('driver_available', models.BooleanField(default=False, verbose_name='chauffeur disponible')),
                ('fuel_policy', models.CharField(default='Plein à plein', help_text='Ex: Plein à plein, Prépayé', max_length=100, verbose_name='politique de carburant')),
                ('mileage_limit', models.PositiveIntegerField(blank=True, help_text='Laisser vide pour kilométrage illimité', null=True, verbose_name='kilométrage limite par jour (km)')),
                ('min_driver_age', models.PositiveIntegerField(default=21, verbose_name='âge minimum du conducteur')),
                ('min_rental_days', models.PositiveIntegerField(default=1, verbose_name='nombre minimum de jours')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_verified', models.BooleanField(default=False, verbose_name='vérifié')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('tres_bon', 'Très bon'), ('bon', 'Bon'), ('correct', 'Correct')], default='bon', max_length=20, verbose_name='état')),
                ('last_maintenance', models.DateField(blank=True, null=True, verbose_name='dernière révision')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='nombre de vues')),
                ('bookings_count', models.PositiveIntegerField(default=0, verbose_name='nombre de réservations')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='note moyenne')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name="nombre d'avis")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='dernière modification')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL, verbose_name='propriétaire')),
            ],
            options={
                'verbose_name': 'véhicule',
                'verbose_name_plural': 'véhicules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VehicleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='vehicles/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='légende')),
                ('is_primary', models.BooleanField(default=False, verbose_name='image principale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="date d'ajout")),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle', verbose_name='véhicule')),
            ],
            options={
                'verbose_name': 'image de véhicule',
                'verbose_name_plural': 'images de véhicule',
                'ordering': ['order', '-is_primary'],
            },
        ),
    ]
