# Generated by Django 6.0.1 on 2026-02-12 18:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_platform_fee_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vehicleimage',
            options={'ordering': ['order', '-is_primary']},
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='bookings_count',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='fuel_policy',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_ac',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_bluetooth',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_child_seat',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_first_aid_kit',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_gps',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_spare_tire',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='has_usb',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_included',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_type',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='mileage_limit',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='min_driver_age',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='min_rental_days',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_with_driver',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='rating_average',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='reviews_count',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='views_count',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='final_price_per_day',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='platform_fee_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='city',
            field=models.CharField(choices=[('abidjan', 'Abidjan'), ('yamoussoukro', 'Yamoussoukro'), ('bouake', 'Bouaké'), ('san_pedro', 'San-Pédro'), ('korhogo', 'Korhogo'), ('daloa', 'Daloa'), ('man', 'Man')], max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deposit',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='doors',
            field=models.PositiveIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(choices=[('essence', 'Essence'), ('diesel', 'Diesel'), ('hybride', 'Hybride'), ('electrique', 'Électrique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='pickup_location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seats',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique', 'Automatique')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('citadine', 'Citadine'), ('berline', 'Berline'), ('suv', 'SUV/4x4'), ('minibus', 'Minibus'), ('pickup', 'Pick-up'), ('moto', 'Moto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vehicleimage',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='vehicles.vehicle'),
        ),
    ]
