# Generated by Django 6.0.1 on 2026-02-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_vehicle_options_alter_vehicleimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
