# Generated by Django 6.0.1 on 2026-02-12 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_vehicle_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='slug',
        ),
    ]
