# Generated by Django 6.0.1 on 2026-02-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_remove_vehicle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
