# Generated by Django 6.0.1 on 2026-01-31 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date de rejet'),
        ),
        migrations.AddField(
            model_name='booking',
            name='rejection_reason',
            field=models.TextField(blank=True, verbose_name='raison de rejet'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='téléphone'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rejected', 'Rejetée'), ('refunded', 'Remboursée')], default='pending', max_length=20, verbose_name='statut'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'start_date'], name='bookings_bo_status_aeddf5_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['content_type', 'object_id', 'status'], name='bookings_bo_content_297bc9_idx'),
        ),
    ]
