# Generated by Django 6.0.1 on 2026-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_rejected_at_booking_rejection_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='transaction_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='numéro de transaction'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('pending_payment_validation', 'En attente de validation paiement'), ('confirmed', 'Confirmée'), ('paid', 'Payée'), ('ongoing', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée'), ('rejected', 'Rejetée'), ('refunded', 'Remboursée')], default='pending', max_length=40, verbose_name='statut'),
        ),
    ]
